CREATE TABLE MITARBEITER(
	MA_NR INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MA_VORNAME VARCHAR(32),
	MA_NACHNAME VARCHAR(64),
	MA_GEBURTSDATUM DATE,
	MA_GESCHLECHT CHAR(1)
);

INSERT INTO `mitarbeiter` (`MA_VORNAME`, `MA_NACHNAME`, `MA_GEBURTSDATUM`, `MA_GESCHLECHT`) 
    VALUES ('Hans', 'Müller', '1995-11-01', 'm');
INSERT INTO `mitarbeiter` (`MA_VORNAME`, `MA_NACHNAME`, `MA_GEBURTSDATUM`, `MA_GESCHLECHT`) 
    VALUES ('Susi', 'Süß', '1990-01-01', 'w');
