CREATE SEQUENCE KONTO_NUMMERN AS INTEGER START WITH 6 
CREATE TABLE KONTEN(K_NUMMER INTEGER NOT NULL PRIMARY KEY,K_BESITZER VARCHAR,K_SALDO DOUBLE,K_LIMIT DOUBLE)
CREATE TABLE SEQUENCE_SELECT(ZERO INTEGER)
INSERT INTO KONTEN VALUES(1,'Hansi',850.0E0,0.0E0)
INSERT INTO KONTEN VALUES(2,'Franz',-950.0E0,1000.0E0)
INSERT INTO KONTEN VALUES(3,'Susi',100.0E0,1000.0E0)
INSERT INTO KONTEN VALUES(4,'Lilly',0.0E0,0.0E0)
INSERT INTO SEQUENCE_SELECT VALUES(0)


