//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("schule2000Model", "FK_pruefungen_gegenstaende", "gegenstaende", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.gegenstaende), "pruefungen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.pruefungen), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_stunden_gegenstaende", "gegenstaende", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.gegenstaende), "stunden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.stunden))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_klassen_lehrer", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.lehrer), "klassen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.klassen))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_klassen_schueler", "schueler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.schueler), "klassen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.klassen))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_klassen_schueler1", "schueler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.schueler), "klassen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.klassen))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_schueler_klassen", "klassen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.klassen), "schueler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.schueler))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_stunden_klassen", "klassen", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.klassen), "stunden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.stunden), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_lehrer_lehrer", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.lehrer), "lehrer1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.lehrer))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_pruefungen_lehrer", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.lehrer), "pruefungen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.pruefungen), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_stunden_lehrer", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.lehrer), "stunden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.stunden))]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_vorgesetzte_lehrer", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.lehrer), "vorgesetzte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.vorgesetzte), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_vorgesetzte_lehrer1", "lehrer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.lehrer), "vorgesetzte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.vorgesetzte), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_pruefungen_schueler", "schueler", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Schule2000.schueler), "pruefungen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.pruefungen), true)]
[assembly: EdmRelationshipAttribute("schule2000Model", "FK_stunden_raeume", "raeume", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Schule2000.raeume), "stunden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Schule2000.stunden))]

#endregion

namespace Schule2000
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class schule2000Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new schule2000Entities object using the connection string found in the 'schule2000Entities' section of the application configuration file.
        /// </summary>
        public schule2000Entities() : base("name=schule2000Entities", "schule2000Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schule2000Entities object.
        /// </summary>
        public schule2000Entities(string connectionString) : base(connectionString, "schule2000Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schule2000Entities object.
        /// </summary>
        public schule2000Entities(EntityConnection connection) : base(connection, "schule2000Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gegenstaende> gegenstaende
        {
            get
            {
                if ((_gegenstaende == null))
                {
                    _gegenstaende = base.CreateObjectSet<gegenstaende>("gegenstaende");
                }
                return _gegenstaende;
            }
        }
        private ObjectSet<gegenstaende> _gegenstaende;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<klassen> klassen
        {
            get
            {
                if ((_klassen == null))
                {
                    _klassen = base.CreateObjectSet<klassen>("klassen");
                }
                return _klassen;
            }
        }
        private ObjectSet<klassen> _klassen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lehrer> lehrer
        {
            get
            {
                if ((_lehrer == null))
                {
                    _lehrer = base.CreateObjectSet<lehrer>("lehrer");
                }
                return _lehrer;
            }
        }
        private ObjectSet<lehrer> _lehrer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pruefungen> pruefungen
        {
            get
            {
                if ((_pruefungen == null))
                {
                    _pruefungen = base.CreateObjectSet<pruefungen>("pruefungen");
                }
                return _pruefungen;
            }
        }
        private ObjectSet<pruefungen> _pruefungen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<raeume> raeume
        {
            get
            {
                if ((_raeume == null))
                {
                    _raeume = base.CreateObjectSet<raeume>("raeume");
                }
                return _raeume;
            }
        }
        private ObjectSet<raeume> _raeume;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<schueler> schueler
        {
            get
            {
                if ((_schueler == null))
                {
                    _schueler = base.CreateObjectSet<schueler>("schueler");
                }
                return _schueler;
            }
        }
        private ObjectSet<schueler> _schueler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stunden> stunden
        {
            get
            {
                if ((_stunden == null))
                {
                    _stunden = base.CreateObjectSet<stunden>("stunden");
                }
                return _stunden;
            }
        }
        private ObjectSet<stunden> _stunden;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vorgesetzte> vorgesetzte
        {
            get
            {
                if ((_vorgesetzte == null))
                {
                    _vorgesetzte = base.CreateObjectSet<vorgesetzte>("vorgesetzte");
                }
                return _vorgesetzte;
            }
        }
        private ObjectSet<vorgesetzte> _vorgesetzte;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gegenstaende EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogegenstaende(gegenstaende gegenstaende)
        {
            base.AddObject("gegenstaende", gegenstaende);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the klassen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToklassen(klassen klassen)
        {
            base.AddObject("klassen", klassen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lehrer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolehrer(lehrer lehrer)
        {
            base.AddObject("lehrer", lehrer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pruefungen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopruefungen(pruefungen pruefungen)
        {
            base.AddObject("pruefungen", pruefungen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the raeume EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToraeume(raeume raeume)
        {
            base.AddObject("raeume", raeume);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the schueler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToschueler(schueler schueler)
        {
            base.AddObject("schueler", schueler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stunden EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostunden(stunden stunden)
        {
            base.AddObject("stunden", stunden);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vorgesetzte EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovorgesetzte(vorgesetzte vorgesetzte)
        {
            base.AddObject("vorgesetzte", vorgesetzte);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="gegenstaende")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gegenstaende : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gegenstaende object.
        /// </summary>
        /// <param name="g_ID">Initial value of the G_ID property.</param>
        public static gegenstaende Creategegenstaende(global::System.String g_ID)
        {
            gegenstaende gegenstaende = new gegenstaende();
            gegenstaende.G_ID = g_ID;
            return gegenstaende;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String G_ID
        {
            get
            {
                return _G_ID;
            }
            set
            {
                if (_G_ID != value)
                {
                    OnG_IDChanging(value);
                    ReportPropertyChanging("G_ID");
                    _G_ID = StructuralObject.SetValidValue(value, false, "G_ID");
                    ReportPropertyChanged("G_ID");
                    OnG_IDChanged();
                }
            }
        }
        private global::System.String _G_ID;
        partial void OnG_IDChanging(global::System.String value);
        partial void OnG_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String G_Bez
        {
            get
            {
                return _G_Bez;
            }
            set
            {
                OnG_BezChanging(value);
                ReportPropertyChanging("G_Bez");
                _G_Bez = StructuralObject.SetValidValue(value, true, "G_Bez");
                ReportPropertyChanged("G_Bez");
                OnG_BezChanged();
            }
        }
        private global::System.String _G_Bez;
        partial void OnG_BezChanging(global::System.String value);
        partial void OnG_BezChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_gegenstaende", "pruefungen")]
        public EntityCollection<pruefungen> pruefungen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_gegenstaende", "pruefungen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_gegenstaende", "pruefungen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_gegenstaende", "stunden")]
        public EntityCollection<stunden> stunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stunden>("schule2000Model.FK_stunden_gegenstaende", "stunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stunden>("schule2000Model.FK_stunden_gegenstaende", "stunden", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="klassen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class klassen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new klassen object.
        /// </summary>
        /// <param name="k_ID">Initial value of the K_ID property.</param>
        public static klassen Createklassen(global::System.String k_ID)
        {
            klassen klassen = new klassen();
            klassen.K_ID = k_ID;
            return klassen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String K_ID
        {
            get
            {
                return _K_ID;
            }
            set
            {
                if (_K_ID != value)
                {
                    OnK_IDChanging(value);
                    ReportPropertyChanging("K_ID");
                    _K_ID = StructuralObject.SetValidValue(value, false, "K_ID");
                    ReportPropertyChanged("K_ID");
                    OnK_IDChanged();
                }
            }
        }
        private global::System.String _K_ID;
        partial void OnK_IDChanging(global::System.String value);
        partial void OnK_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String K_Bez
        {
            get
            {
                return _K_Bez;
            }
            set
            {
                OnK_BezChanging(value);
                ReportPropertyChanging("K_Bez");
                _K_Bez = StructuralObject.SetValidValue(value, true, "K_Bez");
                ReportPropertyChanged("K_Bez");
                OnK_BezChanged();
            }
        }
        private global::System.String _K_Bez;
        partial void OnK_BezChanging(global::System.String value);
        partial void OnK_BezChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_lehrer", "lehrer")]
        public lehrer lehrer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_klassen_lehrer", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_klassen_lehrer", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_klassen_lehrer", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_klassen_lehrer", "lehrer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_schueler", "schueler")]
        public schueler schueler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler", "schueler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler", "schueler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<schueler> schuelerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler", "schueler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<schueler>("schule2000Model.FK_klassen_schueler", "schueler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_schueler1", "schueler")]
        public schueler schueler1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler1", "schueler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler1", "schueler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<schueler> schueler1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_klassen_schueler1", "schueler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<schueler>("schule2000Model.FK_klassen_schueler1", "schueler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_schueler_klassen", "schueler")]
        public EntityCollection<schueler> schueler2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<schueler>("schule2000Model.FK_schueler_klassen", "schueler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<schueler>("schule2000Model.FK_schueler_klassen", "schueler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_klassen", "stunden")]
        public EntityCollection<stunden> stunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stunden>("schule2000Model.FK_stunden_klassen", "stunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stunden>("schule2000Model.FK_stunden_klassen", "stunden", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="lehrer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lehrer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lehrer object.
        /// </summary>
        /// <param name="l_ID">Initial value of the L_ID property.</param>
        public static lehrer Createlehrer(global::System.String l_ID)
        {
            lehrer lehrer = new lehrer();
            lehrer.L_ID = l_ID;
            return lehrer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String L_ID
        {
            get
            {
                return _L_ID;
            }
            set
            {
                if (_L_ID != value)
                {
                    OnL_IDChanging(value);
                    ReportPropertyChanging("L_ID");
                    _L_ID = StructuralObject.SetValidValue(value, false, "L_ID");
                    ReportPropertyChanged("L_ID");
                    OnL_IDChanged();
                }
            }
        }
        private global::System.String _L_ID;
        partial void OnL_IDChanging(global::System.String value);
        partial void OnL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_Name
        {
            get
            {
                return _L_Name;
            }
            set
            {
                OnL_NameChanging(value);
                ReportPropertyChanging("L_Name");
                _L_Name = StructuralObject.SetValidValue(value, true, "L_Name");
                ReportPropertyChanged("L_Name");
                OnL_NameChanged();
            }
        }
        private global::System.String _L_Name;
        partial void OnL_NameChanging(global::System.String value);
        partial void OnL_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_Vorname
        {
            get
            {
                return _L_Vorname;
            }
            set
            {
                OnL_VornameChanging(value);
                ReportPropertyChanging("L_Vorname");
                _L_Vorname = StructuralObject.SetValidValue(value, true, "L_Vorname");
                ReportPropertyChanged("L_Vorname");
                OnL_VornameChanged();
            }
        }
        private global::System.String _L_Vorname;
        partial void OnL_VornameChanging(global::System.String value);
        partial void OnL_VornameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> L_Gebdat
        {
            get
            {
                return _L_Gebdat;
            }
            set
            {
                OnL_GebdatChanging(value);
                ReportPropertyChanging("L_Gebdat");
                _L_Gebdat = StructuralObject.SetValidValue(value, "L_Gebdat");
                ReportPropertyChanged("L_Gebdat");
                OnL_GebdatChanged();
            }
        }
        private Nullable<global::System.DateTime> _L_Gebdat;
        partial void OnL_GebdatChanging(Nullable<global::System.DateTime> value);
        partial void OnL_GebdatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> L_Gehalt
        {
            get
            {
                return _L_Gehalt;
            }
            set
            {
                OnL_GehaltChanging(value);
                ReportPropertyChanging("L_Gehalt");
                _L_Gehalt = StructuralObject.SetValidValue(value, "L_Gehalt");
                ReportPropertyChanged("L_Gehalt");
                OnL_GehaltChanged();
            }
        }
        private Nullable<global::System.Single> _L_Gehalt;
        partial void OnL_GehaltChanging(Nullable<global::System.Single> value);
        partial void OnL_GehaltChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_lehrer", "klassen")]
        public EntityCollection<klassen> klassen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<klassen>("schule2000Model.FK_klassen_lehrer", "klassen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<klassen>("schule2000Model.FK_klassen_lehrer", "klassen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_lehrer_lehrer", "lehrer1")]
        public EntityCollection<lehrer> lehrer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_lehrer_lehrer", "lehrer")]
        public lehrer lehrer2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrer2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_lehrer_lehrer", "lehrer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_lehrer", "pruefungen")]
        public EntityCollection<pruefungen> pruefungen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_lehrer", "pruefungen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_lehrer", "pruefungen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_lehrer", "stunden")]
        public EntityCollection<stunden> stunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stunden>("schule2000Model.FK_stunden_lehrer", "stunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stunden>("schule2000Model.FK_stunden_lehrer", "stunden", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_vorgesetzte_lehrer", "vorgesetzte")]
        public EntityCollection<vorgesetzte> vorgesetzte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vorgesetzte>("schule2000Model.FK_vorgesetzte_lehrer", "vorgesetzte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vorgesetzte>("schule2000Model.FK_vorgesetzte_lehrer", "vorgesetzte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_vorgesetzte_lehrer1", "vorgesetzte")]
        public EntityCollection<vorgesetzte> vorgesetzte1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<vorgesetzte>("schule2000Model.FK_vorgesetzte_lehrer1", "vorgesetzte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<vorgesetzte>("schule2000Model.FK_vorgesetzte_lehrer1", "vorgesetzte", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="pruefungen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pruefungen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pruefungen object.
        /// </summary>
        /// <param name="p_Datum">Initial value of the P_Datum property.</param>
        /// <param name="p_S_Kandidat">Initial value of the P_S_Kandidat property.</param>
        /// <param name="p_L_Pruefer">Initial value of the P_L_Pruefer property.</param>
        /// <param name="p_G_Fach">Initial value of the P_G_Fach property.</param>
        public static pruefungen Createpruefungen(global::System.DateTime p_Datum, global::System.Int16 p_S_Kandidat, global::System.String p_L_Pruefer, global::System.String p_G_Fach)
        {
            pruefungen pruefungen = new pruefungen();
            pruefungen.P_Datum = p_Datum;
            pruefungen.P_S_Kandidat = p_S_Kandidat;
            pruefungen.P_L_Pruefer = p_L_Pruefer;
            pruefungen.P_G_Fach = p_G_Fach;
            return pruefungen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime P_Datum
        {
            get
            {
                return _P_Datum;
            }
            set
            {
                if (_P_Datum != value)
                {
                    OnP_DatumChanging(value);
                    ReportPropertyChanging("P_Datum");
                    _P_Datum = StructuralObject.SetValidValue(value, "P_Datum");
                    ReportPropertyChanged("P_Datum");
                    OnP_DatumChanged();
                }
            }
        }
        private global::System.DateTime _P_Datum;
        partial void OnP_DatumChanging(global::System.DateTime value);
        partial void OnP_DatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 P_S_Kandidat
        {
            get
            {
                return _P_S_Kandidat;
            }
            set
            {
                if (_P_S_Kandidat != value)
                {
                    OnP_S_KandidatChanging(value);
                    ReportPropertyChanging("P_S_Kandidat");
                    _P_S_Kandidat = StructuralObject.SetValidValue(value, "P_S_Kandidat");
                    ReportPropertyChanged("P_S_Kandidat");
                    OnP_S_KandidatChanged();
                }
            }
        }
        private global::System.Int16 _P_S_Kandidat;
        partial void OnP_S_KandidatChanging(global::System.Int16 value);
        partial void OnP_S_KandidatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String P_L_Pruefer
        {
            get
            {
                return _P_L_Pruefer;
            }
            set
            {
                if (_P_L_Pruefer != value)
                {
                    OnP_L_PrueferChanging(value);
                    ReportPropertyChanging("P_L_Pruefer");
                    _P_L_Pruefer = StructuralObject.SetValidValue(value, false, "P_L_Pruefer");
                    ReportPropertyChanged("P_L_Pruefer");
                    OnP_L_PrueferChanged();
                }
            }
        }
        private global::System.String _P_L_Pruefer;
        partial void OnP_L_PrueferChanging(global::System.String value);
        partial void OnP_L_PrueferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String P_G_Fach
        {
            get
            {
                return _P_G_Fach;
            }
            set
            {
                if (_P_G_Fach != value)
                {
                    OnP_G_FachChanging(value);
                    ReportPropertyChanging("P_G_Fach");
                    _P_G_Fach = StructuralObject.SetValidValue(value, false, "P_G_Fach");
                    ReportPropertyChanged("P_G_Fach");
                    OnP_G_FachChanged();
                }
            }
        }
        private global::System.String _P_G_Fach;
        partial void OnP_G_FachChanging(global::System.String value);
        partial void OnP_G_FachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String P_Art
        {
            get
            {
                return _P_Art;
            }
            set
            {
                OnP_ArtChanging(value);
                ReportPropertyChanging("P_Art");
                _P_Art = StructuralObject.SetValidValue(value, true, "P_Art");
                ReportPropertyChanged("P_Art");
                OnP_ArtChanged();
            }
        }
        private global::System.String _P_Art;
        partial void OnP_ArtChanging(global::System.String value);
        partial void OnP_ArtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> P_Note
        {
            get
            {
                return _P_Note;
            }
            set
            {
                OnP_NoteChanging(value);
                ReportPropertyChanging("P_Note");
                _P_Note = StructuralObject.SetValidValue(value, "P_Note");
                ReportPropertyChanged("P_Note");
                OnP_NoteChanged();
            }
        }
        private Nullable<global::System.Byte> _P_Note;
        partial void OnP_NoteChanging(Nullable<global::System.Byte> value);
        partial void OnP_NoteChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_gegenstaende", "gegenstaende")]
        public gegenstaende gegenstaende
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_pruefungen_gegenstaende", "gegenstaende").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_pruefungen_gegenstaende", "gegenstaende").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gegenstaende> gegenstaendeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_pruefungen_gegenstaende", "gegenstaende");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gegenstaende>("schule2000Model.FK_pruefungen_gegenstaende", "gegenstaende", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_lehrer", "lehrer")]
        public lehrer lehrer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_pruefungen_lehrer", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_pruefungen_lehrer", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_pruefungen_lehrer", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_pruefungen_lehrer", "lehrer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_schueler", "schueler")]
        public schueler schueler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_pruefungen_schueler", "schueler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_pruefungen_schueler", "schueler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<schueler> schuelerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<schueler>("schule2000Model.FK_pruefungen_schueler", "schueler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<schueler>("schule2000Model.FK_pruefungen_schueler", "schueler", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="raeume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class raeume : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new raeume object.
        /// </summary>
        /// <param name="r_ID">Initial value of the R_ID property.</param>
        public static raeume Createraeume(global::System.String r_ID)
        {
            raeume raeume = new raeume();
            raeume.R_ID = r_ID;
            return raeume;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String R_ID
        {
            get
            {
                return _R_ID;
            }
            set
            {
                if (_R_ID != value)
                {
                    OnR_IDChanging(value);
                    ReportPropertyChanging("R_ID");
                    _R_ID = StructuralObject.SetValidValue(value, false, "R_ID");
                    ReportPropertyChanged("R_ID");
                    OnR_IDChanged();
                }
            }
        }
        private global::System.String _R_ID;
        partial void OnR_IDChanging(global::System.String value);
        partial void OnR_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> R_Plaetze
        {
            get
            {
                return _R_Plaetze;
            }
            set
            {
                OnR_PlaetzeChanging(value);
                ReportPropertyChanging("R_Plaetze");
                _R_Plaetze = StructuralObject.SetValidValue(value, "R_Plaetze");
                ReportPropertyChanged("R_Plaetze");
                OnR_PlaetzeChanged();
            }
        }
        private Nullable<global::System.Int16> _R_Plaetze;
        partial void OnR_PlaetzeChanging(Nullable<global::System.Int16> value);
        partial void OnR_PlaetzeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_raeume", "stunden")]
        public EntityCollection<stunden> stunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stunden>("schule2000Model.FK_stunden_raeume", "stunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stunden>("schule2000Model.FK_stunden_raeume", "stunden", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="schueler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class schueler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new schueler object.
        /// </summary>
        /// <param name="s_SCHNR">Initial value of the S_SCHNR property.</param>
        public static schueler Createschueler(global::System.Int16 s_SCHNR)
        {
            schueler schueler = new schueler();
            schueler.S_SCHNR = s_SCHNR;
            return schueler;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 S_SCHNR
        {
            get
            {
                return _S_SCHNR;
            }
            set
            {
                if (_S_SCHNR != value)
                {
                    OnS_SCHNRChanging(value);
                    ReportPropertyChanging("S_SCHNR");
                    _S_SCHNR = StructuralObject.SetValidValue(value, "S_SCHNR");
                    ReportPropertyChanged("S_SCHNR");
                    OnS_SCHNRChanged();
                }
            }
        }
        private global::System.Int16 _S_SCHNR;
        partial void OnS_SCHNRChanging(global::System.Int16 value);
        partial void OnS_SCHNRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_Name
        {
            get
            {
                return _S_Name;
            }
            set
            {
                OnS_NameChanging(value);
                ReportPropertyChanging("S_Name");
                _S_Name = StructuralObject.SetValidValue(value, true, "S_Name");
                ReportPropertyChanged("S_Name");
                OnS_NameChanged();
            }
        }
        private global::System.String _S_Name;
        partial void OnS_NameChanging(global::System.String value);
        partial void OnS_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_Vorname
        {
            get
            {
                return _S_Vorname;
            }
            set
            {
                OnS_VornameChanging(value);
                ReportPropertyChanging("S_Vorname");
                _S_Vorname = StructuralObject.SetValidValue(value, true, "S_Vorname");
                ReportPropertyChanged("S_Vorname");
                OnS_VornameChanged();
            }
        }
        private global::System.String _S_Vorname;
        partial void OnS_VornameChanging(global::System.String value);
        partial void OnS_VornameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> S_Gebdat
        {
            get
            {
                return _S_Gebdat;
            }
            set
            {
                OnS_GebdatChanging(value);
                ReportPropertyChanging("S_Gebdat");
                _S_Gebdat = StructuralObject.SetValidValue(value, "S_Gebdat");
                ReportPropertyChanged("S_Gebdat");
                OnS_GebdatChanged();
            }
        }
        private Nullable<global::System.DateTime> _S_Gebdat;
        partial void OnS_GebdatChanging(Nullable<global::System.DateTime> value);
        partial void OnS_GebdatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_Adresse
        {
            get
            {
                return _S_Adresse;
            }
            set
            {
                OnS_AdresseChanging(value);
                ReportPropertyChanging("S_Adresse");
                _S_Adresse = StructuralObject.SetValidValue(value, true, "S_Adresse");
                ReportPropertyChanged("S_Adresse");
                OnS_AdresseChanged();
            }
        }
        private global::System.String _S_Adresse;
        partial void OnS_AdresseChanging(global::System.String value);
        partial void OnS_AdresseChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_schueler", "klassen")]
        public EntityCollection<klassen> klassen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<klassen>("schule2000Model.FK_klassen_schueler", "klassen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<klassen>("schule2000Model.FK_klassen_schueler", "klassen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_klassen_schueler1", "klassen")]
        public EntityCollection<klassen> klassen1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<klassen>("schule2000Model.FK_klassen_schueler1", "klassen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<klassen>("schule2000Model.FK_klassen_schueler1", "klassen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_schueler_klassen", "klassen")]
        public klassen klassen2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_schueler_klassen", "klassen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_schueler_klassen", "klassen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<klassen> klassen2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_schueler_klassen", "klassen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<klassen>("schule2000Model.FK_schueler_klassen", "klassen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_pruefungen_schueler", "pruefungen")]
        public EntityCollection<pruefungen> pruefungen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_schueler", "pruefungen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pruefungen>("schule2000Model.FK_pruefungen_schueler", "pruefungen", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="stunden")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stunden : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stunden object.
        /// </summary>
        /// <param name="sT_K_Klasse">Initial value of the ST_K_Klasse property.</param>
        /// <param name="sT_Stunde">Initial value of the ST_Stunde property.</param>
        public static stunden Createstunden(global::System.String sT_K_Klasse, global::System.String sT_Stunde)
        {
            stunden stunden = new stunden();
            stunden.ST_K_Klasse = sT_K_Klasse;
            stunden.ST_Stunde = sT_Stunde;
            return stunden;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ST_K_Klasse
        {
            get
            {
                return _ST_K_Klasse;
            }
            set
            {
                if (_ST_K_Klasse != value)
                {
                    OnST_K_KlasseChanging(value);
                    ReportPropertyChanging("ST_K_Klasse");
                    _ST_K_Klasse = StructuralObject.SetValidValue(value, false, "ST_K_Klasse");
                    ReportPropertyChanged("ST_K_Klasse");
                    OnST_K_KlasseChanged();
                }
            }
        }
        private global::System.String _ST_K_Klasse;
        partial void OnST_K_KlasseChanging(global::System.String value);
        partial void OnST_K_KlasseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ST_Stunde
        {
            get
            {
                return _ST_Stunde;
            }
            set
            {
                if (_ST_Stunde != value)
                {
                    OnST_StundeChanging(value);
                    ReportPropertyChanging("ST_Stunde");
                    _ST_Stunde = StructuralObject.SetValidValue(value, false, "ST_Stunde");
                    ReportPropertyChanged("ST_Stunde");
                    OnST_StundeChanged();
                }
            }
        }
        private global::System.String _ST_Stunde;
        partial void OnST_StundeChanging(global::System.String value);
        partial void OnST_StundeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_gegenstaende", "gegenstaende")]
        public gegenstaende gegenstaende
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_stunden_gegenstaende", "gegenstaende").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_stunden_gegenstaende", "gegenstaende").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gegenstaende> gegenstaendeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gegenstaende>("schule2000Model.FK_stunden_gegenstaende", "gegenstaende");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gegenstaende>("schule2000Model.FK_stunden_gegenstaende", "gegenstaende", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_klassen", "klassen")]
        public klassen klassen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_stunden_klassen", "klassen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_stunden_klassen", "klassen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<klassen> klassenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<klassen>("schule2000Model.FK_stunden_klassen", "klassen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<klassen>("schule2000Model.FK_stunden_klassen", "klassen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_lehrer", "lehrer")]
        public lehrer lehrer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_stunden_lehrer", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_stunden_lehrer", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_stunden_lehrer", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_stunden_lehrer", "lehrer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_stunden_raeume", "raeume")]
        public raeume raeume
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<raeume>("schule2000Model.FK_stunden_raeume", "raeume").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<raeume>("schule2000Model.FK_stunden_raeume", "raeume").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<raeume> raeumeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<raeume>("schule2000Model.FK_stunden_raeume", "raeume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<raeume>("schule2000Model.FK_stunden_raeume", "raeume", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schule2000Model", Name="vorgesetzte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vorgesetzte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vorgesetzte object.
        /// </summary>
        /// <param name="v_L_Vorg">Initial value of the V_L_Vorg property.</param>
        /// <param name="v_Art">Initial value of the V_Art property.</param>
        /// <param name="v_L_Unt">Initial value of the V_L_Unt property.</param>
        public static vorgesetzte Createvorgesetzte(global::System.String v_L_Vorg, global::System.String v_Art, global::System.String v_L_Unt)
        {
            vorgesetzte vorgesetzte = new vorgesetzte();
            vorgesetzte.V_L_Vorg = v_L_Vorg;
            vorgesetzte.V_Art = v_Art;
            vorgesetzte.V_L_Unt = v_L_Unt;
            return vorgesetzte;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String V_L_Vorg
        {
            get
            {
                return _V_L_Vorg;
            }
            set
            {
                if (_V_L_Vorg != value)
                {
                    OnV_L_VorgChanging(value);
                    ReportPropertyChanging("V_L_Vorg");
                    _V_L_Vorg = StructuralObject.SetValidValue(value, false, "V_L_Vorg");
                    ReportPropertyChanged("V_L_Vorg");
                    OnV_L_VorgChanged();
                }
            }
        }
        private global::System.String _V_L_Vorg;
        partial void OnV_L_VorgChanging(global::System.String value);
        partial void OnV_L_VorgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String V_Art
        {
            get
            {
                return _V_Art;
            }
            set
            {
                if (_V_Art != value)
                {
                    OnV_ArtChanging(value);
                    ReportPropertyChanging("V_Art");
                    _V_Art = StructuralObject.SetValidValue(value, false, "V_Art");
                    ReportPropertyChanged("V_Art");
                    OnV_ArtChanged();
                }
            }
        }
        private global::System.String _V_Art;
        partial void OnV_ArtChanging(global::System.String value);
        partial void OnV_ArtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String V_L_Unt
        {
            get
            {
                return _V_L_Unt;
            }
            set
            {
                if (_V_L_Unt != value)
                {
                    OnV_L_UntChanging(value);
                    ReportPropertyChanging("V_L_Unt");
                    _V_L_Unt = StructuralObject.SetValidValue(value, false, "V_L_Unt");
                    ReportPropertyChanged("V_L_Unt");
                    OnV_L_UntChanged();
                }
            }
        }
        private global::System.String _V_L_Unt;
        partial void OnV_L_UntChanging(global::System.String value);
        partial void OnV_L_UntChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_vorgesetzte_lehrer", "lehrer")]
        public lehrer lehrer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer", "lehrer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schule2000Model", "FK_vorgesetzte_lehrer1", "lehrer")]
        public lehrer lehrer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer1", "lehrer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer1", "lehrer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lehrer> lehrer1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer1", "lehrer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lehrer>("schule2000Model.FK_vorgesetzte_lehrer1", "lehrer", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
