CREATE TABLE ARTIKEL (
  a_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  a_warenkorb_id INTEGER UNSIGNED NULL,
  a_bezeichnung VARCHAR(128) NULL,
  a_preis FLOAT NULL,
  a_anzahl INTEGER UNSIGNED NULL,
  PRIMARY KEY(a_id)
);

