CREATE TABLE VORSTELLUNGEN (
  v_id INTEGER UNSIGNED NOT NULL,
  v_datum DATETIME NULL,
  v_name VARCHAR(128) NULL,
  PRIMARY KEY(v_id)
);

CREATE TABLE RESERVIERUNGEN (
  r_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  fk_v_id INTEGER UNSIGNED NOT NULL,
  r_sitzplatz INTEGER UNSIGNED NULL,
  r_name VARCHAR(128) NULL,
  PRIMARY KEY(r_id, fk_v_id),
  INDEX RESERVIERUNGEN_FKIndex1(fk_v_id),
  FOREIGN KEY(fk_v_id)
    REFERENCES VORSTELLUNGEN(v_id)
);





INSERT INTO VORSTELLUNGEN VALUES(1,'2010-03-20','Der kleine Prinz');
INSERT INTO VORSTELLUNGEN VALUES(2,'2010-03-21','Rumplestilzchen');
INSERT INTO VORSTELLUNGEN VALUES(3,'2010-03-22','Schneewittchen');
INSERT INTO VORSTELLUNGEN VALUES(4,'2010-03-23','Der gestiefelte Kater');
INSERT INTO VORSTELLUNGEN VALUES(6,'2010-03-20','Rotkäppchen');
