//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schule2000wpf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Schule2000Entities : DbContext
    {
        public Schule2000Entities()
            : base("name=Schule2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gegenstaende> gegenstaende { get; set; }
        public DbSet<klassen> klassen { get; set; }
        public DbSet<lehrer> lehrer { get; set; }
        public DbSet<pruefungen> pruefungen { get; set; }
        public DbSet<raeume> raeume { get; set; }
        public DbSet<schueler> schueler { get; set; }
        public DbSet<stunden> stunden { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<vorgesetzte> vorgesetzte { get; set; }
    }
}
