//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schule2000ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasse
    {
        public Klasse()
        {
            this.schueler = new HashSet<Schueler>();
            this.stunden = new HashSet<stunden>();
        }
    
        public string K_ID { get; set; }
        public string K_Bez { get; set; }
    
        public virtual lehrer lehrer { get; set; }
        public virtual Schueler klassensprecher { get; set; }
        public virtual Schueler stellvertreter { get; set; }
        public virtual ICollection<Schueler> schueler { get; set; }
        public virtual ICollection<stunden> stunden { get; set; }
    }
}
