//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorien
    {
        public kategorien()
        {
            this.kategorien1 = new HashSet<kategorien>();
            this.produkte = new HashSet<produkte>();
        }
    
        public int kat_id { get; set; }
        public string kat_name { get; set; }
        public byte[] kat_version { get; set; }
    
        public virtual ICollection<kategorien> kategorien1 { get; set; }
        public virtual kategorien kategorien2 { get; set; }
        public virtual ICollection<produkte> produkte { get; set; }
    }
}
