//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechnungen
    {
        public int r_nummer { get; set; }
        public Nullable<System.DateTime> r_datum { get; set; }
        public byte[] r_version { get; set; }
    
        public virtual Adresse adressen { get; set; }
        public virtual bestellungen bestellungen { get; set; }
        public virtual konto_buchungen konto_buchungen { get; set; }
    }
}
