//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class warenkorb_positionen
    {
        public int fk_wp_warenkorb { get; set; }
        public int fk_wp_produkt { get; set; }
        public int wp_menge { get; set; }
        public byte[] wp_version { get; set; }
    
        public virtual produkte produkte { get; set; }
        public virtual warenkoerbe warenkoerbe { get; set; }
    }
}
