CREATE SEQUENCE MITARBEITERNUMMER AS INTEGER START WITH 1 
CREATE MEMORY TABLE MITARBEITER(MA_NR INTEGER NOT NULL PRIMARY KEY,MA_VORNAME VARCHAR(32),MA_NACHNAME VARCHAR(64),MA_GEBURTSDATUM TIMESTAMP,MA_GESCHLECHT CHAR(1))
CREATE MEMORY TABLE DUMMY(DUMMY INTEGER)
INSERT INTO DUMMY VALUES(1)
