//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public Adresse()
        {
            this.bestellungen = new HashSet<bestellungen>();
            this.rechnungen = new HashSet<rechnungen>();
            this.standorte = new HashSet<standorte>();
        }
    
        public int a_id { get; set; }
        public string a_strasse { get; set; }
        public string a_ort { get; set; }
        public int a_plz { get; set; }
        public byte[] a_version { get; set; }
    
        public virtual kunden kunden { get; set; }
        public virtual laender laender { get; set; }
        public virtual ICollection<bestellungen> bestellungen { get; set; }
        public virtual ICollection<rechnungen> rechnungen { get; set; }
        public virtual ICollection<standorte> standorte { get; set; }
    }
}
