//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class laender
    {
        public laender()
        {
            this.adressen = new HashSet<Adresse>();
        }
    
        public string l_code { get; set; }
        public string l_name { get; set; }
        public byte[] l_version { get; set; }
    
        public virtual ICollection<Adresse> adressen { get; set; }
    }
}
