//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Webshop : DbContext
    {
        public Webshop()
            : base("name=Webshop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresse> adressen { get; set; }
        public DbSet<benutzer> benutzer { get; set; }
        public DbSet<bestellungen> bestellungen { get; set; }
        public DbSet<einkaufs_positionen> einkaufs_positionen { get; set; }
        public DbSet<kategorien> kategorien { get; set; }
        public DbSet<konto_buchungen> konto_buchungen { get; set; }
        public DbSet<kunden> kunden { get; set; }
        public DbSet<laender> laender { get; set; }
        public DbSet<lagerpositionen> lagerpositionen { get; set; }
        public DbSet<produkte> produkte { get; set; }
        public DbSet<rechnungen> rechnungen { get; set; }
        public DbSet<reklamationen> reklamationen { get; set; }
        public DbSet<standorte> standorte { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<telefonnummern> telefonnummern { get; set; }
        public DbSet<warenkoerbe> warenkoerbe { get; set; }
        public DbSet<warenkorb_positionen> warenkorb_positionen { get; set; }
    }
}
