//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class benutzer
    {
        public benutzer()
        {
            this.kunden = new HashSet<kunden>();
        }
    
        public string ben_name { get; set; }
        public string ben_kennwort { get; set; }
        public string ben_typ { get; set; }
        public byte[] ben_version { get; set; }
    
        public virtual ICollection<kunden> kunden { get; set; }
    }
}
