//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class bestellungen
    {
        public bestellungen()
        {
            this.rechnungen = new HashSet<rechnungen>();
            this.reklamationen = new HashSet<reklamationen>();
        }
    
        public int b_id { get; set; }
        public System.DateTime b_datum { get; set; }
        public Nullable<System.DateTime> b_versand_datum { get; set; }
        public byte[] b_version { get; set; }
    
        public virtual Adresse adressen { get; set; }
        public virtual warenkoerbe warenkoerbe { get; set; }
        public virtual ICollection<rechnungen> rechnungen { get; set; }
        public virtual ICollection<reklamationen> reklamationen { get; set; }
    }
}
