//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class einkaufs_positionen
    {
        public int ep_id { get; set; }
        public int ep_anzahl { get; set; }
        public byte[] ep_version { get; set; }
    
        public virtual konto_buchungen konto_buchungen { get; set; }
        public virtual produkte produkte { get; set; }
        public virtual standorte standorte { get; set; }
    }
}
