//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class lagerpositionen
    {
        public int fk_lp_standort { get; set; }
        public int fk_lp_produkt { get; set; }
        public int lp_anzahl { get; set; }
        public byte[] lp_version { get; set; }
    
        public virtual produkte produkte { get; set; }
        public virtual standorte standorte { get; set; }
    }
}
