//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkte
    {
        public produkte()
        {
            this.einkaufs_positionen = new HashSet<einkaufs_positionen>();
            this.lagerpositionen = new HashSet<lagerpositionen>();
            this.reklamationen = new HashSet<reklamationen>();
            this.warenkorb_positionen = new HashSet<warenkorb_positionen>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_mengeneinheit { get; set; }
        public double p_einkaufspreis { get; set; }
        public double p_verkaufspreis { get; set; }
        public byte[] p_version { get; set; }
    
        public virtual ICollection<einkaufs_positionen> einkaufs_positionen { get; set; }
        public virtual kategorien kategorien { get; set; }
        public virtual ICollection<lagerpositionen> lagerpositionen { get; set; }
        public virtual ICollection<reklamationen> reklamationen { get; set; }
        public virtual ICollection<warenkorb_positionen> warenkorb_positionen { get; set; }
    }
}
