//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class reklamationen
    {
        public int rek_id { get; set; }
        public Nullable<System.DateTime> rek_datum { get; set; }
        public Nullable<int> rek_menge { get; set; }
        public string rek_status { get; set; }
        public string rek_bemerkung { get; set; }
        public byte[] rek_version { get; set; }
    
        public virtual bestellungen bestellungen { get; set; }
        public virtual konto_buchungen konto_buchungen { get; set; }
        public virtual produkte produkte { get; set; }
    }
}
