//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class standorte
    {
        public standorte()
        {
            this.einkaufs_positionen = new HashSet<einkaufs_positionen>();
            this.lagerpositionen = new HashSet<lagerpositionen>();
        }
    
        public int s_id { get; set; }
        public string s_name { get; set; }
        public byte[] s_version { get; set; }
    
        public virtual Adresse adressen { get; set; }
        public virtual ICollection<einkaufs_positionen> einkaufs_positionen { get; set; }
        public virtual ICollection<lagerpositionen> lagerpositionen { get; set; }
    }
}
