//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class konto_buchungen
    {
        public konto_buchungen()
        {
            this.einkaufs_positionen = new HashSet<einkaufs_positionen>();
            this.rechnungen = new HashSet<rechnungen>();
            this.reklamationen = new HashSet<reklamationen>();
        }
    
        public int kb_id { get; set; }
        public double kb_betrag { get; set; }
        public string kb_text { get; set; }
        public System.DateTime kb_datum { get; set; }
        public byte[] kb_version { get; set; }
    
        public virtual ICollection<einkaufs_positionen> einkaufs_positionen { get; set; }
        public virtual ICollection<rechnungen> rechnungen { get; set; }
        public virtual ICollection<reklamationen> reklamationen { get; set; }
    }
}
