//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunden
    {
        public kunden()
        {
            this.adressen = new HashSet<Adresse>();
            this.telefonnummern = new HashSet<telefonnummern>();
            this.warenkoerbe = new HashSet<warenkoerbe>();
        }
    
        public int k_id { get; set; }
        public string k_name { get; set; }
        public string k_email { get; set; }
        public byte[] k_version { get; set; }
    
        public virtual ICollection<Adresse> adressen { get; set; }
        public virtual benutzer benutzer { get; set; }
        public virtual ICollection<telefonnummern> telefonnummern { get; set; }
        public virtual ICollection<warenkoerbe> warenkoerbe { get; set; }
    }
}
