//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityConcurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class warenkoerbe
    {
        public warenkoerbe()
        {
            this.bestellungen = new HashSet<bestellungen>();
            this.warenkorb_positionen = new HashSet<warenkorb_positionen>();
        }
    
        public int w_id { get; set; }
        public byte[] w_version { get; set; }
    
        public virtual ICollection<bestellungen> bestellungen { get; set; }
        public virtual kunden kunden { get; set; }
        public virtual ICollection<warenkorb_positionen> warenkorb_positionen { get; set; }
    }
}
